\documentclass{article}
\usepackage{graphicx}

\begin{document}

\section{Appendix}
Here is the text of your introduction.

\begin{tabular}{l|cc}
	Name & Stuff & Stuff \\\\
	\\hline
	a & b & c \\\\
	
    $colormap:{x|$x.name$ & \\includegraphics[height=2cm]{$x.images$\} & C \\\\ }; separator = "\n"$   
	
\end{tabular}

\subsection{Subsection Heading Here}
Write your subsection text here.

\section{Conclusion}
Write your conclusion here.

\end{document}
